name: GKE Deploy Django App

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: YOUR_DOCKER_HUB_USERNAME/YOUR_IMAGE_NAME
  K8S_NAMESPACE: default
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  authenticate:
    name: Authenticate with Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          
      - name: Authenticate with GKE
        run: |
          gcloud config set project $GCP_PROJECT_ID
          gcloud config set compute/zone $GKE_CLUSTER_ZONE
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: authenticate

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t $DOCKER_IMAGE:latest .

      - name: Push Docker Image
        run: docker push $DOCKER_IMAGE:latest

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: [authenticate, build]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
